#ifndef MY_COLOR_SEGMENTATION_ENUM_H
#define MY_COLOR_SEGMENTATION_ENUM_H
enum colorLabels{
	MYCOLOR_RED = 0,
	MYCOLOR_ORANGE = 1,
	MYCOLOR_YELLOW = 2,
	MYCOLOR_LIGHT_GREEN = 3,
	MYCOLOR_DARK_GREEN = 4,
	MYCOLOR_CYAN = 5,
	MYCOLOR_LIGHT_BLUE = 6,
	MYCOLOR_DARK_BLUE = 7,
	MYCOLOR_VIOLET = 8,
	MYCOLOR_MAGENTA = 9,
	MYCOLOR_PINK = 10,
	MYCOLOR_BLACK = 11,
	MYCOLOR_WHITE = 12,
	MYCOLOR_OTHERS = 13,
};
#endif MY_COLOR_SEGMENTATION_ENUM_H